service: localstack-lambda
plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x

functions:
  hello:
    handler: bin/hello
    events:
    - http:
        path: hello
        method: get